### ISSUE TITLE
 vignettes/pcrfree_vs_nano.subset.csv Missing

### ISSUE THREAD

**Issue by ShrutiMarwaha** [Illumina/happyCompare#1]
Hi,

The 'vignettes/pcrfree_vs_nano.subset.csv' given in quickstart guide example seems to be missing from package. When I load happyCompare library, I encounter the following error.

Commands:
devtools::install_github("Illumina/happyCompare")
library(happyCompare)
samplesheet_path <- "vignettes/pcrfree_vs_nano.subset.csv"
happy_compare <- read_samplesheet(samplesheet_path, lazy = TRUE)

Error:
Reading happyCompare samplesheet
Error in read_samplesheet(samplesheet_path, lazy = TRUE) : 
  Cannot find samplesheet: vignettes/pcrfree_vs_nano.subset.csv

When I try to search for for any cv file in happyCompare package, I find pcrfree_vs_nano.tests.csv. However, providing that path to read_samplesheet also gives an error. 

Command: 
samplesheet_path <- system.file('tests','testthat','pcrfree_vs_nano.tests.csv', package='happyCompare')
happy_compare <- read_samplesheet(samplesheet_path, lazy = TRUE)
Error:
Reading happyCompare samplesheet
Parsed with column specification:
cols(
  Group.Id = col_character(),
  Sample.Id = col_character(),
  Replicate.Id = col_character(),
  happy_prefix = col_character(),
  build_metrics = col_character()
)
Processing ../data/pcrfree_vs_nano/filtered_happy/NA12878-I30_S1
Error in check_happy_path(happy_prefix) : 
  Can't read directory: ../data/pcrfree_vs_nano/filtered_happy

Command: find  /Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare/ -name "*.csv" -print
Output: 
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/build_metrics/NA12878-I30_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/build_metrics/NA12878-I33_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/build_metrics/NA12878-R1_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/build_metrics/NA12878-R2_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-I30_S1.extended.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-I30_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-I33_S1.extended.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-I33_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-R1_S1.extended.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-R1_S1.summary.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-R2_S1.extended.csv
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/data/pcrfree_vs_nano/filtered_happy/NA12878-R2_S1.summary.csv
**/Library/Frameworks/R.framework/Versions/3.4/Resources/library/happyCompare//tests/testthat/pcrfree_vs_nano.tests.csv**

Thanks,
Shruti

Shruti Marwaha, PhD.
Research Engineer,
Stanford Center for Undiagnosed Diseases
Stanford University

**Comment by ShrutiMarwaha** [comment]
How is the input to read_samplesheet generated? from hap.py?

**Comment by mgonzalezporta** [comment]
Hi @ShrutiMarwaha,

In order to load the `pcrfree_vs_nano.subset.csv` samplesheet using relative paths, you'll first need to set the working directory to the happyCompare root:
```
setwd("/path/to/happyCompare-master")
samplesheet_path <- "vignettes/pcrfree_vs_nano.subset.csv"
happy_compare <- read_samplesheet(samplesheet_path, lazy = TRUE)
```

Alternatively, you can work directly with the pre-packaged demo dataset:
```
happy_compare <- readRDS("vignettes/pcrfree_vs_nano.subset.Rds")
```

Finally, you can check the contents of the samplesheet here:
https://github.com/Illumina/happyCompare/blob/master/vignettes/pcrfree_vs_nano.subset.csv

You'll need to generate it manually. These fields are required:
- `Group.Id`, `Sample.Id`, `Replicate.Id`: custom metadata fields.
- `happy_prefix`: path to hap.py results (prefix only). E.g. if your hap.py summary.csv output is `/path/to/happy/NA12878-I30_S1.summary.csv`, you need to provide `/path/to/happy/NA12878-I30_S1`.

Additionally, you can provide paths to metrics csv using the `build_metrics` field, which will be loaded together with hap.py results. Any other columns that you add to the samplesheet will also be available as metadata when querying the `happy_compare` object.

Hope this helps. 

Cheers,

Mar

**Comment by ShrutiMarwaha** [comment]
Thanks Mar @mgonzalezporta, that worked. Sorry for the delayed response.

**Comment by mgonzalezporta** [comment]
Great news, closing the issue.
